[package]
name = "rusqlite-ext"
version = "0.39.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "This is a Rusqlite extension for building the FTS5 tokenizer."
keywords = ["SQLite", "Extension", "Rusqlite", "Tokenizer"]
readme = "README.md"
repository = "https://github.com/lukingcathy/sqlite-simple-tokenizer"

[lib]
path = "lib.rs"

[dependencies]
log = { workspace = true }
rusqlite = { workspace = true }
